import RPi.GPIO as gpio
import time
import sys


def clear():
    gpio.output(7, False)
    gpio.output(11, False)
    gpio.output(13, False)
    gpio.output(15, False)

def init():
    gpio.setmode(gpio.BOARD)
    gpio.setup(7, gpio.OUT)
    gpio.setup(11, gpio.OUT)
    gpio.setup(13, gpio.OUT)
    gpio.setup(15, gpio.OUT)
    gpio.setup(24, gpio.OUT)
    gpio.setup(22, gpio.OUT)

def forward(tf):
    init()
    gpio.output(7, True)
    gpio.output(11, False)
    gpio.output(13, False)
    gpio.output(15, True)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    clear()
    gpio.cleanup()

def reverse(tf):
    init()
    gpio.output(7, False)
    gpio.output(11, True)
    gpio.output(13, True)
    gpio.output(15, False)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    clear()
    gpio.cleanup()

def turn_left(tf):
    init()
    gpio.output(7, False)
    gpio.output(11, False)
    gpio.output(13, False)
    gpio.output(15, True)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    clear()
    gpio.cleanup()

def turn_right(tf):
    init()
    gpio.output(7, True)
    gpio.output(11, False)
    gpio.output(13, True)
    gpio.output(15, True)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    clear()
    gpio.cleanup()

def pivot_left(tf):
    init()
    gpio.output(7, False)
    gpio.output(11, True)
    gpio.output(13, False)
    gpio.output(15, True)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    clear()
    gpio.cleanup()

def pivot_right(tf):
    init()
    gpio.output(7, True)
    gpio.output(11, False)
    gpio.output(13, True)
    gpio.output(15, False)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    clear()
    gpio.cleanup()

def hold(tf):
    init()
    gpio.output(7, False)
    gpio.output(11, False)
    gpio.output(13, False)
    gpio.output(15, False)
    gpio.output(24, True)
    gpio.output(22, True)
    time.sleep(tf)
    gpio.output(24, False)
    gpio.output(22, False)
    gpio.cleanup()

if __name__ == "__main__":
    #pivot_right(3)
    #time.sleep(0.5)
    forward(3)
    time.sleep(0.5)
    #reverse(3)
    #time.sleep(0.5)
    turn_left(3)
    time.sleep(0.5)
    forward(3)
    time.sleep(0.5)
    #turn_left(3)
    #pivot_left(3)
    #time.sleep(1)
    #pivot_right(3)
